<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'SlmMail\Module'                          => __DIR__ . '/Module.php',
    'SlmMail\Service\Mailchimp\Sts'           => __DIR__ . '/src/SlmMail/Service/Mailchimp/Sts.php',
    'SlmMail\Service\Mailchimp\Campaign'      => __DIR__ . '/src/SlmMail/Service/Mailchimp/Campaign.php',
    'SlmMail\Service\SendGrid'                => __DIR__ . '/src/SlmMail/Service/SendGrid.php',
    'SlmMail\Service\Amazon'                  => __DIR__ . '/src/SlmMail/Service/Amazon.php',
    'SlmMail\Service\Postmark'                => __DIR__ . '/src/SlmMail/Service/Postmark.php',
    'SlmMail\Service\Postage'                 => __DIR__ . '/src/SlmMail/Service/Postage.php',
    'SlmMail\Service\AmazonSes'               => __DIR__ . '/src/SlmMail/Service/AmazonSes.php',
    'SlmMail\Service\ElasticEmail'            => __DIR__ . '/src/SlmMail/Service/ElasticEmail.php',
    'SlmMail\Mail\Message\Postmark'           => __DIR__ . '/src/SlmMail/Mail/Message/Postmark.php',
    'SlmMail\Mail\Message\Postage'            => __DIR__ . '/src/SlmMail/Mail/Message/Postage.php',
    'SlmMail\Mail\Message\Mailchimp'          => __DIR__ . '/src/SlmMail/Mail/Message/Mailchimp.php',
    'SlmMail\Mail\Message\ElasticEmail'       => __DIR__ . '/src/SlmMail/Mail/Message/ElasticEmail.php',
    'SlmMail\Mail\Transport\SendGrid'         => __DIR__ . '/src/SlmMail/Mail/Transport/SendGrid.php',
    'SlmMail\Mail\Transport\Postmark'         => __DIR__ . '/src/SlmMail/Mail/Transport/Postmark.php',
    'SlmMail\Mail\Transport\Postage'          => __DIR__ . '/src/SlmMail/Mail/Transport/Postage.php',
    'SlmMail\Mail\Transport\AmazonSes'        => __DIR__ . '/src/SlmMail/Mail/Transport/AmazonSes.php',
    'SlmMail\Mail\Transport\Mailchimp'        => __DIR__ . '/src/SlmMail/Mail/Transport/Mailchimp.php',
    'SlmMail\Mail\Transport\ElasticEmail'     => __DIR__ . '/src/SlmMail/Mail/Transport/ElasticEmail.php',
    'SlmMailTest\Mail\Transport\PostmarkTest' => __DIR__ . '/tests/SlmMailTest/Mail/Transport/PostmarkTest.php',
);